[package]
name = "rust"
version = "0.1.0"
authors = ["JiZhi <2590970043@qq.com>"]
edition = "2018"

[dependencies]
jni = "0.18.0"
magic-crypt = "3.1.6"
base64 = "0.13.0"
[lib]
crate_type = ["staticlib", "dylib"]